# Project 01: Student Performance Analysis

This project explores student performance data using NumPy.

## Part 1: Data Analysis with NumPy

In [1]:
import numpy as np

# Creating NumPy Arrays

In [2]:
marks = np.array([65, 72, 80, 58, 90])
marks

array([65, 72, 80, 58, 90])

# Basic statistics

In [3]:
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))

Mean: 73.0
Median: 72.0
Standard Deviation: 11.20714058089752
Max: 90
Min: 58


# Vectorised Operations

In [4]:
adjusted_marks = marks + 5
adjusted_marks

array([70, 77, 85, 63, 95])

# Logical conditions on arrays

In [5]:
pass_mask = marks >= 50
pass_mask

array([ True,  True,  True,  True,  True])

In [6]:
passed_students = marks[pass_mask]
passed_students

array([65, 72, 80, 58, 90])

# Mini Task Practice

In [7]:
results = np.array([ 10, 19, 12, 54, 33, 45, 98, 44, 70, 23 ])
results

array([10, 19, 12, 54, 33, 45, 98, 44, 70, 23])

In [8]:
print("Mean:", np.mean(results))
print("Sttandard Deviation:", np.std(results))

Mean: 40.8
Sttandard Deviation: 26.377262936097065


# Printing out values above the mean after clear observation

In [14]:
values_above_mean = np.array([ 54, 45, 98, 44, 70 ])
values_above_mean

array([54, 45, 98, 44, 70])

## Part 2: Data Analysis with Pandas

In [1]:
import pandas as pd

## Table of data

In [32]:
data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [65, 72, 80, 58, 90]
}

df = pd.DataFrame(data)
df

Student  Marks
0       A     65
1       B     72
2       C     80
3       D     58
4       E     90

## Basic Inspection

In [3]:
df.head()

Student  Marks
0       A     65
1       B     72
2       C     80
3       D     58
4       E     90

In [4]:
df.describe()

Marks
count   5.000000
mean   73.000000
std    12.529964
min    58.000000
25%    65.000000
50%    72.000000
75%    80.000000
max    90.000000

## Filtering data

In [5]:
df[df["Marks"] >= 50]

Student  Marks
0       A     65
1       B     72
2       C     80
3       D     58
4       E     90

In [6]:
df[df["Marks"] < 50]

Empty DataFrame
Columns: [Student, Marks]
Index: []

## Adding a new column

In [11]:
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 50 else "Fail")
df

Student  Marks result Result
0       A     65   Pass   Pass
1       B     72   Pass   Pass
2       C     80   Pass   Pass
3       D     58   Pass   Pass
4       E     90   Pass   Pass

## Mini Task Practice

In [27]:
data = {
    "Student": [ "Rifuwo", "Kenny", "Junior", "Lucas", "Michelle"],
    "Marks": [ 69, 41, 85, 72, 33]
}

df = pd.DataFrame(data)
df

Student  Marks
0    Rifuwo     69
1     Kenny     41
2    Junior     85
3     Lucas     72
4  Michelle     33

In [28]:
mean_marks = df["Marks"].mean()
max_marks = df["Marks"].max()

mean_marks, max_marks

(np.float64(60.0), np.int64(85))

In [30]:
def assign_grade(mark):
    if mark >= 75:
        return "A"
    elif mark >= 65:
        return "B"
    elif mark >= 50:
        return "C"
    else:
        return "Fail"

In [31]:
df["Grade"] = df["Marks"].apply(assign_grade)
df

Student  Marks Grade
0    Rifuwo     69     B
1     Kenny     41  Fail
2    Junior     85     A
3     Lucas     72     B
4  Michelle     33  Fail

## Summary

- Calculated average and maximum marks
- Cleaned numeric data
- Assigned grades based on performance